spring:
  application:
    name: app

  flyway:
    locations: classpath:/db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/admin2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC
    password: root
    username: root
#    schema-username: root
#    data-username: root
  data:
    redis:
      host: localhost
      port: 6379
      password:
      username:
      database: 0

logging:
  level:
    root: DEBUG
    org.springframework.jdbc.core: TRACE
    com.xfrog: DEBUG

#springdoc:
#  api-docs:
#    enabled: true
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

admin:
  auth-server:
    enablePasswordGrant: true