databaseChangeLog:
  - changeSet:
      id: 2024-06-03-0001
      author: hb
      context: prod
      labels: oauth2_authorization-table
      changes:
        - createTable:
            tableName: oauth2_authorization
            columns:
              - column:
                  name: id
                  type: varchar(100)
                  constraints:
                    nullable: false
                    primaryKey: true
              - column:
                  name: registered_client_id
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: principal_name
                  type: varchar(200)
                  constraints:
                    nullable: false
              - column:
                  name: authorization_grant_type
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: authorized_scopes
                  type: varchar(1000)
                  defaultValue: NULL
              - column:
                  name: attributes
                  type: blob
                  defaultValue: NULL
              - column:
                  name: state
                  type: varchar(500)
                  defaultValue: NULL
              - column:
                  name: authorization_code_value
                  type: blob
                  defaultValue: NULL
              - column:
                  name: authorization_code_issued_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: authorization_code_expires_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: authorization_code_metadata
                  type: blob
                  defaultValue: NULL
              - column:
                  name: access_token_value
                  type: blob
                  defaultValue: NULL
              - column:
                  name: access_token_issued_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: access_token_expires_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: access_token_metadata
                  type: blob
                  defaultValue: NULL
              - column:
                  name: access_token_type
                  type: varchar(100)
                  defaultValue: NULL
              - column:
                  name: access_token_scopes
                  type: varchar(1000)
                  defaultValue: NULL
              - column:
                  name: oidc_id_token_value
                  type: blob
                  defaultValue: NULL
              - column:
                  name: oidc_id_token_issued_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: oidc_id_token_expires_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: oidc_id_token_metadata
                  type: blob
                  defaultValue: NULL
              - column:
                  name: refresh_token_value
                  type: blob
                  defaultValue: NULL
              - column:
                  name: refresh_token_issued_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: refresh_token_expires_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: refresh_token_metadata
                  type: blob
                  defaultValue: NULL
              - column:
                  name: user_code_value
                  type: blob
                  defaultValue: NULL
              - column:
                  name: user_code_issued_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: user_code_expires_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: user_code_metadata
                  type: blob
                  defaultValue: NULL
              - column:
                  name: device_code_value
                  type: blob
                  defaultValue: NULL
              - column:
                  name: device_code_issued_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: device_code_expires_at
                  type: timestamp
                  defaultValue: NULL
              - column:
                  name: device_code_metadata
                  type: blob
                  defaultValue: NULL
        - createIndex:
            tableName: oauth2_authorization
            indexName: idx_oauth2_authorization_principal_name
            labels: oauth2_authorization-table
            unique: false
            columns:
              - column:
                  name: principal_name