databaseChangeLog:
  - changeSet:
      id: 2024-06-25-0001
      author: hb
      comments: Create OAuth2 Sessions table
      context: prod
      labels: oauth2-sessions-table
      changes:
        - createTable:
            tableName: oauth2_sessions
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
                    comment: 'ID'
              - column:
                  name: session_id
                  type: varchar(64)
                  constraints:
                    nullable: false
                    comment: '会话ID'
              - column:
                  name: session_id_hash
                  type: varchar(64)
                  constraints:
                    nullable: true
                    comment: '会话ID哈希'
              - column:
                  name: authorization_id
                  type: varchar(100)
                  constraints:
                    nullable: true
                    comment: '关联的认证ID'
              - column:
                  name: user_id
                  type: bigint
                  constraints:
                    nullable: false
                    comment: '用户ID'
              - column:
                  name: last_request
                  type: datetime(3)
                  constraints:
                    nullable: true
                    comment: '最后请求日期'
              - column:
                  name: principal_id
                  type: bigint
                  constraints:
                    nullable: true
                    comment: '关联身份信息ID'
              - column:
                  name: expired
                  type: TINYINT
                  remarks: 是否过期
                  constraints:
                    nullable: false
                  defaultValue: 0
              - column:
                  name: created_time
                  type: timestamp
                  constraints:
                    nullable: false
                    comment: '创建时间'
              - column:
                  name: updated_time
                  type: timestamp
                  constraints:
                    nullable: false
                    comment: '更新时间'
        - createIndex:
            indexName: idx_oauth2_session_session_id
            tableName: oauth2_sessions
            unique: false
            columns:
              - column:
                  name: session_id
        - createIndex:
            indexName: idx_oauth2_session_session_id_hash
            tableName: oauth2_sessions
            unique: false
            columns:
              - column:
                  name: session_id_hash
        - createIndex:
            indexName: idx_oauth2_session_authorization_id
            tableName: oauth2_sessions
            unique: false
            columns:
              - column:
                  name: authorization_id
        - createTable:
            tableName: oauth2_principals
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
                    comment: 'ID'
              - column:
                  name: user_id
                  type: bigint
                  constraints:
                    nullable: false
                    comment: '用户ID'
              - column:
                  name: principal_info
                  type: varchar(512)
                  constraints:
                    nullable: true
                    comment: '用户信息'
              - column:
                  name: created_time
                  type: timestamp
                  constraints:
                    nullable: false
                    comment: '创建时间'
              - column:
                  name: updated_time
                  type: timestamp
                  constraints:
                    nullable: false
                    comment: '更新时间'
        - createIndex:
            indexName: idx_oauth2_principals_user_id
            tableName: oauth2_principals
            unique: false
            columns:
              - column:
                  name: user_id