databaseChangeLog:
  - changeSet:
      id: 2024-06-01-organizations-0001
      author: hb
      comments: Create Organizations table
      context: prod
      labels: organizations-table
      changes:
        - createTable:
            tableName: organizations
            columns:
              - column:
                  name: id
                  type: BIGINT
                  remarks: 组织ID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(128)
                  remarks: 组织名称
                  constraints:
                    nullable: false
              - column:
                  name: parent_id
                  type: BIGINT
                  remarks: 父组织ID
              - column:
                  name: parent_ids
                  type: VARCHAR(512)
                  remarks: 父组织ID列表
                  constraints:
                    nullable: true
              - column:
                  name: code
                  type: VARCHAR(256)
                  remarks: 组织编码
                  constraints:
                    nullable: false
              - column:
                  name: level
                  type: INT
                  remarks: 组织层级
                  constraints:
                    nullable: false
              - column:
                  name: seq
                  type: INT
                  remarks: 组织排序
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(32)
                  remarks: 组织状态
                  constraints:
                    nullable: false
              - column:
                  name: display_order
                  type: INT
                  remarks: 显示顺序
                  constraints:
                    nullable: false
                  defaultValue: 100
              - column:
                  name: telephone
                  type: VARCHAR(64)
                  remarks: 联系电话
                  constraints:
                    nullable: true
              - column:
                  name: principal
                  type: VARCHAR(64)
                  remarks: 负责人
                  constraints:
                    nullable: true
              - column:
                  name: tenant_id
                  type: VARCHAR(64)
                  remarks: 租户
                  constraints:
                    nullable: false
                  defaultValue: 'GLOBAL'
              - column:
                  name: created_by
                  type: BIGINT
                  remarks: 创建人
                  constraints:
                    nullable: false
              - column:
                  name: created_time
                  type: TIMESTAMP
                  remarks: 创建时间
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_by
                  type: BIGINT
                  remarks: 更新人
                  constraints:
                    nullable: false
              - column:
                  name: updated_time
                  type: TIMESTAMP
                  remarks: 更新时间
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: deleted
                  type: TINYINT
                  remarks: 是否删除
                  constraints:
                    nullable: false
                  defaultValue: 0
              - column:
                  name: deleted_by
                  type: BIGINT
                  remarks: 删除人
              - column:
                  name: deleted_time
                  type: TIMESTAMP
                  remarks: 删除时间
        - addUniqueConstraint:
            constraintName: idx_organizations_code_tenant_id
            tableName: organizations
            columnNames: code, tenant_id
  - changeSet:
      id: 2024-06-04-organizations-0001
      author: hb
      context: prod
      labels: organizations-table
      changes:
        - insert:
            tableName: organizations
            columns:
              - column:
                  name: id
                  valueComputed: 1
              - column:
                  name: name
                  value: 'GLOBAL'
              - column:
                  name: parent_id
                  value: NULL
              - column:
                  name: code
                  value: '0001'
              - column:
                  name: level
                  valueNumeric: 1
              - column:
                  name: seq
                  valueNumeric: 1
              - column:
                  name: status
                  value: 'NORMAL'
              - column:
                  name: display_order
                  valueNumeric: 1
              - column:
                  name: telephone
                  value: null
              - column:
                  name: principal
                  value: null
              - column:
                  name: tenant_id
                  value: 'GLOBAL'
              - column:
                  name: created_by
                  valueNumeric: 1
              - column:
                  name: created_time
                  valueDate: '2024-06-04 08:54:40'
              - column:
                  name: updated_by
                  valueNumeric: 1
              - column:
                  name: updated_time
                  valueDate: '2024-06-04 08:54:40'
              - column:
                  name: deleted
                  valueNumeric: 0
              - column:
                  name: deleted_by
                  value: NULL
              - column:
                  name: deleted_time
                  value: NULL