databaseChangeLog:
  - changeSet:
      id: 2024-06-01-roles-0001
      author: hb
      comments: 创建roles表
      context: prod
      labels: roles-table
      changes:
        - createTable:
            tableName: roles
            columns:
              - column:
                  name: id
                  type: BIGINT
                  remarks: 角色ID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(128)
                  remarks: 角色名称
                  constraints:
                    nullable: false
              - column:
                  name: memo
                  type: VARCHAR(256)
                  remarks: 角色说明
                  constraints:
                    nullable: true
              - column:
                  name: enabled
                  type: TINYINT
                  defaultValue: 0
              - column:
                  name: tenant_id
                  type: VARCHAR(64)
                  remarks: 租户
                  constraints:
                    nullable: false
                  defaultValue: 'GLOBAL'
              - column:
                  name: created_by
                  type: BIGINT
                  remarks: 创建人
                  constraints:
                    nullable: false
              - column:
                  name: created_time
                  type: TIMESTAMP
                  remarks: 创建时间
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_by
                  type: BIGINT
                  remarks: 更新人
                  constraints:
                    nullable: false
              - column:
                  name: updated_time
                  type: TIMESTAMP
                  remarks: 更新时间
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: deleted
                  type: TINYINT
                  remarks: 是否删除标志
                  constraints:
                    nullable: false
                  defaultValue: 0
              - column:
                  name: deleted_by
                  type: BIGINT
                  remarks: 删除人
                  constraints:
                    nullable: true
              - column:
                  name: deleted_time
                  type: TIMESTAMP
                  remarks: 删除时间
                  constraints:
                    nullable: true