databaseChangeLog:
  - changeSet:
      id: 2024-06-01-users-0001
      author: hb
      context: prod
      labels: users-table
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_name
                  type: VARCHAR(128)
                  constraints:
                    nullable: false
              - column:
                  name: password
                  type: VARCHAR(512)
                  constraints:
                    nullable: false
              - column:
                  name: organization_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: account_non_expired
                  type: TINYINT
                  constraints:
                    nullable: false
                  defaultValue: 1
              - column:
                  name: account_non_locked
                  type: TINYINT
                  constraints:
                    nullable: false
                  defaultValue: 1
              - column:
                  name: credentials_non_expired
                  type: TINYINT
                  constraints:
                    nullable: false
                  defaultValue: 1
              - column:
                  name: enabled
                  type: TINYINT
                  constraints:
                    nullable: false
                  defaultValue: 1
              - column:
                  name: name
                  type: VARCHAR(128)
                  constraints:
                    nullable: false
              - column:
                  name: sex
                  type: VARCHAR(32)
              - column:
                  name: mobile_phone
                  type: VARCHAR(32)
              - column:
                  name: email
                  type: VARCHAR(128)
              - column:
                  name: last_login_time
                  type: TIMESTAMP
              - column:
                  name: tenant_id
                  type: VARCHAR(64)
                  constraints:
                    nullable: false
                  defaultValue: 'GLOBAL'
              - column:
                  name: created_by
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: created_time
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_by
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: updated_time
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: deleted
                  type: TINYINT
                  constraints:
                    nullable: false
                  defaultValue: 0
              - column:
                  name: deleted_by
                  type: BIGINT
              - column:
                  name: deleted_time
                  type: TIMESTAMP
        - addUniqueConstraint:
            constraintName: idx_users_username_tenant_id
            tableName: users
            columnNames: user_name, tenant_id
  - changeSet:
      id: 2024-06-01-users-0002
      author: hb
      context: prod
      labels: users-table
      changes:
        - insert:
            tableName: users
            columns:
              - column:
                  name: id
                  valueNumeric: 1
              - column:
                  name: user_name
                  value: 'admin'
              - column:
                  name: password
                  value: '{bcrypt}$2a$10$uzOkfsxFQ2ymJDj45l0fvu0tqakbMyDDAw7dC1iuna3GXAgm/ZHIC' #admin#123
              - column:
                  name: organization_id
                  valueNumeric: 1
              - column:
                  name: account_non_expired
                  valueNumeric: 1
              - column:
                  name: account_non_locked
                  valueNumeric: 1
              - column:
                  name: credentials_non_expired
                  valueNumeric: 1
              - column:
                  name: enabled
                  valueNumeric: 1
              - column:
                  name: name
                  value: '管理员'
              - column:
                  name: sex
                  value: null
              - column:
                  name: mobile_phone
                  value: null
              - column:
                  name: email
                  value: null
              - column:
                  name: last_login_time
                  valueDate: '2024-06-03 14:49:33'
              - column:
                  name: tenant_id
                  value: 'GLOBAL'
              - column:
                  name: created_by
                  valueNumeric: 1
              - column:
                  name: created_time
                  valueDate: '2024-06-03 14:49:33'
              - column:
                  name: updated_by
                  valueNumeric: 1
              - column:
                  name: updated_time
                  valueDate: '2024-06-03 14:49:33'
              - column:
                  name: deleted
                  valueNumeric: 0
              - column:
                  name: deleted_by
                  value: null
              - column:
                  name: deleted_time
                  valueDate: null